export enum UserApplicationStatus {
  NOT_STARTED = "NOT_STARTED",
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  WAITLISTED = "WAITLISTED",
  CONFIRMED_RSVP = "CONFIRMED_RSVP",
} 