// TICKET
const ticketDescription =
  "This is your ticket for the event and will be needed to register (a.k.a. check in) at Garuda Hacks 2024. You will need to check in at least twice out of the three 12 hour intervals throughout the event. Please press 'View my ticket', then use the buttons below to add this ticket to your mobile wallet or take a screenshot of the ticket page. \n\n Registration begins at 5 PM local time in the Lobby of Universitas Multimedia Nusantara Main Building.";

// APPLICATION
const applicationIntro =
  "Garuda Hacks would not be where it is today without its participants, and we are always impressed and humbled by the quality and enthusiasm of our applicants. Founded in 2020, we have since hosted five successful hackathons with over 8,200 participants and disbursed a total of 800 million IDR to support creative tech projects. This year, we are humbled to offer a prize pool of 160 million IDR, but we recognize that our impact goes far beyond monetary awards—it's about building a community that learns and grows together.\n\nWe take our application process very seriously. Every week, we form dedicated reading committees to review each submission carefully and get to know you beyond your résumé. Because demand far exceeds the number of slots we can fill, we review applications based on the effort you put in rather than existing qualifications. We encourage you to share your passion, describe your ideas in detail, and show us the enthusiasm that drives you—your dedication matters more than any title or credential.\n\nWe know that, at times, things may not go perfectly, and we want you to understand that we value transparency and humility above all. If something goes sideways during the event, we promise to listen, learn, and make it right—because Garuda Hacks exists for you, and we care deeply about your experience.\n\nWe plan to start releasing decisions on June 20 and will continue sending acceptances on a rolling basis thereafter. We read and appreciate every application, and we will get back to you as soon as possible. Press continue to start your application.";

export { ticketDescription, applicationIntro };
